# -*- coding: utf-8 -*-
"""mf_database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKutx2qRyL6e4eXNKYPaAU1hh9sKArAt
"""

import mysql.connector
from datetime import datetime

#create connection
try: 
  mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="sqlroot",
      database="mfguide"
  )
except Exception as error:
  print('Error while creating connection', error)
  


def database_insertion(all_mfs_info, database_all_mf_info):
    zip_object = zip(all_mfs_info, database_all_mf_info)
    for mf, db_insert_info in zip_object:
        print(mf)
        print(db_insert_info[0])
        print(db_insert_info[1])

        id_category = 0
        id_mutual_fund = 0

        cursor = mydb.cursor(buffered=True)
         
         # checking if the category exists
        check_if_exists_cat = "SELECT name FROM category where name = %s"
        vals_to_match_cat = [db_insert_info[1]]
        cursor.execute(check_if_exists_cat, vals_to_match_cat)
        if_exists = cursor.fetchall()
        if not if_exists:
            insert_category = "INSERT INTO category (name) VALUES (%s)"
            cursor.execute(insert_category, vals_to_match_cat)
            mydb.commit()
            print("inserted category")

            # getting the id
            check_if_exists_cat_id = "SELECT id FROM category where name = %s"
            vals_to_match_cat_id = [db_insert_info[1]]
            cursor.execute(check_if_exists_cat_id, vals_to_match_cat_id)

            id_category = cursor.fetchall()[0]
        else:
            # getting the id
            check_if_exists_cat_id = "SELECT id FROM category where name = %s"
            vals_to_match_cat_id = [db_insert_info[1]]
            cursor.execute(check_if_exists_cat_id, vals_to_match_cat_id)

            id_category = cursor.fetchall()[0]
            print(id_category)
        print(id_category)
        print(id_category[0])
        print(type(id_category[0]))


        # cursor.execute("SELECT id FROM category")
        # id_category = cursor.fetchone()
        # print("category id ", id_category[0])


        # cheking if the mutual fund exists
        check_if_exists_mf_name = "SELECT name FROM mutual_fund where name = %s"
        vals_to_match_mf_name = [db_insert_info[0]]
        cursor.execute(check_if_exists_mf_name, vals_to_match_mf_name)
        if_exists = cursor.fetchall()
        if not if_exists:
            insert_category = "INSERT INTO mutual_fund (name, category_id) VALUES (%s, %s)"
            #insert_vals = (db_insert_info[0], id_category)
            #insert_vals_list = list(insert_vals)
            cursor.execute(insert_category, (str(db_insert_info[0]), id_category[0]))#insert_vals_list)
            mydb.commit()
            print("inserted mutual fund")

            # getting the id
            check_if_exists_mf_name_id = "SELECT id FROM mutual_fund where name = %s"
            vals_to_match_mf_name_id = [db_insert_info[0]]
            cursor.execute(check_if_exists_mf_name_id, vals_to_match_mf_name_id)
            id_mutual_fund = cursor.fetchall()[0]
        else:
            print(if_exists)
            check_if_exists_mf_name_id = "SELECT id FROM mutual_fund where name = %s"
            vals_to_match_mf_name_id = [db_insert_info[0]]
            cursor.execute(check_if_exists_mf_name_id, vals_to_match_mf_name_id)
            id_mutual_fund = cursor.fetchall()[0]

        # cursor.execute("SELECT id FROM mutual_fund")
        # id_mutual_fund = cursor.fetchone()
        # print("mutual_fund id ", id_mutual_fund[0])
        # print(type(id_mutual_fund[0]))

        cursor.execute("SELECT id FROM data_provider")
        id_data_provider = cursor.fetchone()
        print("data_provider id ", id_data_provider[0])

        # using now() to get current time
        current_time = datetime.now()

        print("Time now is : ", end="")
        print(current_time)

        mySql_insert_query = """INSERT INTO mfdata (mutual_fund_id, data_provider_id, asof_date, rating, launch, first, third, fifth, er, asset, mean, stddev, sharpe, sortiono, beta, alpha)
        VALUES (%s, %s, %s , %s, %s, %s, %s, %s, %s, %s, %s , %s, %s, %s, %s, %s)"""

        # mySql_insert_query = """("INSERT INTO mfdata" "(mutual_fund_id, data_provider_id, asof_date,)"
        # "VALUES (%d, %d, %s)")"""

        # mySql_insert_query = "INSERT INTO mfdata (mutual_fund_id, data_provider_id,asof_date) values(%s, %s, %s)"
        
        # record = [id_mutual_fund[0], id_data_provider[0], current_time]
        record = []
        record.extend([id_mutual_fund[0], id_data_provider[0], current_time])
        record.extend(mf)

        # print(*record, sep="\n")
        # ls = [type(item) for item in record]
        # print(ls)

        cursor.execute(mySql_insert_query, record)
        mydb.commit()
        print("Record inserted successfully into table")